<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php $statusLabel = 'Status'; ?>
<?php $statusCode = $block->getCustomer()->getCustomAttribute('customer_status')->getAttributeCode(); ?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/saveStatus')) ?>"
      method="post" id="form-validate" enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset status">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field field-name-firstname required">
            <label class="label"
                   for="<?= $statusCode ?>"><span><?= $statusLabel ?></span></label>
            <div class="control">
                <input type="text" id="<?= $statusCode ?>"
                       name="<?= $statusCode ?>"
                       value="<?= $block->getCustomer()->getCustomAttribute('customer_status')->getValue() ?>"
                       title="<?= $statusLabel ?>"
                       class="input-text">
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset"></fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>

</form>
